<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [
            ['province_id' => 1, 'name' => 'Aceh Barat'], 
            ['province_id' => 1, 'name' => 'Aceh Barat Daya'], 
            ['province_id' => 1, 'name' => 'Aceh Besar'], 
            ['province_id' => 1, 'name' => 'Aceh Jaya'], 
            ['province_id' => 1, 'name' => 'Aceh Selatan'], 
            ['province_id' => 1, 'name' => 'Aceh Singkil'], 
            ['province_id' => 1, 'name' => 'Aceh Tamiang'], 
            ['province_id' => 1, 'name' => 'Aceh Tengah'], 
            ['province_id' => 1, 'name' => 'Aceh Tenggara'], 
            ['province_id' => 1, 'name' => 'Aceh Timur'], 
            ['province_id' => 1, 'name' => 'Aceh Utara'], 
            ['province_id' => 1, 'name' => 'Banda Aceh'], 
            ['province_id' => 1, 'name' => 'Bener Meriah'], 
            ['province_id' => 1, 'name' => 'Bireuen'], 
            ['province_id' => 1, 'name' => 'Gayo Lues'], 
            ['province_id' => 1, 'name' => 'Langsa'], 
            ['province_id' => 1, 'name' => 'Lhokseumawe'], 
            ['province_id' => 1, 'name' => 'Nagan Raya'], 
            ['province_id' => 1, 'name' => 'Pidie'], 
            ['province_id' => 1, 'name' => 'Pidie Jaya'], 
            ['province_id' => 1, 'name' => 'Sabang'], 
            ['province_id' => 1, 'name' => 'Simeulue'], 
            ['province_id' => 1, 'name' => 'Subulussalam'],
            ['province_id' => 2, 'name' => 'Badung'], 
            ['province_id' => 2, 'name' => 'Bangli'], 
            ['province_id' => 2, 'name' => 'Buleleng'], 
            ['province_id' => 2, 'name' => 'Denpasar'], 
            ['province_id' => 2, 'name' => 'Gianyar'], 
            ['province_id' => 2, 'name' => 'Jembrana'], 
            ['province_id' => 2, 'name' => 'Karangasem'], 
            ['province_id' => 2, 'name' => 'Klungkung'], 
            ['province_id' => 2, 'name' => 'Tabanan'], 
            ['province_id' => 3, 'name' => 'Bangka'],
            ['province_id' => 3, 'name' => 'Bangka Barat'],
            ['province_id' => 3, 'name' => 'Bangka Selatan'],
            ['province_id' => 3, 'name' => 'Bangka Tengah'],
            ['province_id' => 3, 'name' => 'Belitung'],
            ['province_id' => 3, 'name' => 'Belitung Timur'],
            ['province_id' => 3, 'name' => 'Pangkal Pinang'],
            ['province_id' => 4, 'name' => 'Cilegon'], 
            ['province_id' => 4, 'name' => 'Lebak'], 
            ['province_id' => 4, 'name' => 'Pandeglang'], 
            ['province_id' => 4, 'name' => 'Serang'], 
            ['province_id' => 4, 'name' => 'Tangerang'], 
            ['province_id' => 4, 'name' => 'Tangerang Selatan'], 
            ['province_id' => 5, 'name' => 'Bengkulu'],  
            ['province_id' => 5, 'name' => 'Bengkulu Selatan'],  
            ['province_id' => 5, 'name' => 'Bengkulu Tengah'],  
            ['province_id' => 5, 'name' => 'Bengkulu Utara'],  
            ['province_id' => 5, 'name' => 'Kaur'],  
            ['province_id' => 5, 'name' => 'Kepahing'],  
            ['province_id' => 5, 'name' => 'Lebong'],  
            ['province_id' => 5, 'name' => 'Mukomuko'],  
            ['province_id' => 5, 'name' => 'Rejang Lebong'],  
            ['province_id' => 5, 'name' => 'Seluma'],  
            ['province_id' => 6, 'name' => 'Gunung Kidul'],
            ['province_id' => 6, 'name' => 'Kulon Progo'],
            ['province_id' => 6, 'name' => 'Sleman'],
            ['province_id' => 6, 'name' => 'Yogyakarta'],
            ['province_id' => 7, 'name' => 'Boalemo'], 
            ['province_id' => 7, 'name' => 'Bone Bolango'], 
            ['province_id' => 7, 'name' => 'Gorontalo'], 
            ['province_id' => 7, 'name' => 'Gorontalo Utara'], 
            ['province_id' => 7, 'name' => 'Pohuwato'], 
            ['province_id' => 8, 'name' => 'Jakarta Barat'], 
            ['province_id' => 8, 'name' => 'Jakarta Pusat'], 
            ['province_id' => 8, 'name' => 'Jakarta Selatan'], 
            ['province_id' => 8, 'name' => 'Jakarta Timur'], 
            ['province_id' => 8, 'name' => 'Jakarta Utara'], 
            ['province_id' => 8, 'name' => 'Kepulauan Seribu'], 
            ['province_id' => 9, 'name' => 'Batanghari'],
            ['province_id' => 9, 'name' => 'Bungo'],
            ['province_id' => 9, 'name' => 'Jambi'],
            ['province_id' => 9, 'name' => 'Kerinci'],
            ['province_id' => 9, 'name' => 'Merangin'],
            ['province_id' => 9, 'name' => 'Muaro Jambi'],
            ['province_id' => 9, 'name' => 'Tanjung Jabung Barat'],
            ['province_id' => 9, 'name' => 'Tanjung Jabung Timur'],
            ['province_id' => 9, 'name' => 'Tebo'],
            ['province_id' => 10, 'name' => 'Bandung'], 
            ['province_id' => 10, 'name' => 'Bandung Barat'], 
            ['province_id' => 10, 'name' => 'Banjar'], 
            ['province_id' => 10, 'name' => 'Bekasi'], 
            ['province_id' => 10, 'name' => 'Bogor'], 
            ['province_id' => 10, 'name' => 'Ciamis'], 
            ['province_id' => 10, 'name' => 'Cianjur'], 
            ['province_id' => 10, 'name' => 'Cimahi'], 
            ['province_id' => 10, 'name' => 'Cirebon'], 
            ['province_id' => 10, 'name' => 'Depok'], 
            ['province_id' => 10, 'name' => 'Garut'], 
            ['province_id' => 10, 'name' => 'Indramayu'], 
            ['province_id' => 10, 'name' => 'Karawang'], 
            ['province_id' => 10, 'name' => 'Kuningan'], 
            ['province_id' => 10, 'name' => 'Majalengka'], 
            ['province_id' => 10, 'name' => 'Purwakarta'], 
            ['province_id' => 10, 'name' => 'Subang'], 
            ['province_id' => 10, 'name' => 'Sukabumi'], 
            ['province_id' => 10, 'name' => 'Sumedang'], 
            ['province_id' => 10, 'name' => 'Tasikmalaya'],
            ['province_id' => 11, 'name' => 'Banjarnegara'], 
            ['province_id' => 11, 'name' => 'Banyumas'], 
            ['province_id' => 11, 'name' => 'Batang'], 
            ['province_id' => 11, 'name' => 'Blora'], 
            ['province_id' => 11, 'name' => 'Boyolali'], 
            ['province_id' => 11, 'name' => 'Brebes'], 
            ['province_id' => 11, 'name' => 'Cilacap'], 
            ['province_id' => 11, 'name' => 'Demak'], 
            ['province_id' => 11, 'name' => 'Grobogan'], 
            ['province_id' => 11, 'name' => 'Jepara'], 
            ['province_id' => 11, 'name' => 'Karanganyar'], 
            ['province_id' => 11, 'name' => 'Kebumen'], 
            ['province_id' => 11, 'name' => 'Kendal'], 
            ['province_id' => 11, 'name' => 'Klaten'], 
            ['province_id' => 11, 'name' => 'Kudus'], 
            ['province_id' => 11, 'name' => 'Magelang'], 
            ['province_id' => 11, 'name' => 'Pati'], 
            ['province_id' => 11, 'name' => 'Pekalongan'], 
            ['province_id' => 11, 'name' => 'Pemalang'], 
            ['province_id' => 11, 'name' => 'Purbalingga'], 
            ['province_id' => 11, 'name' => 'Purworejo'], 
            ['province_id' => 11, 'name' => 'Rembang'], 
            ['province_id' => 11, 'name' => 'Salatiga'], 
            ['province_id' => 11, 'name' => 'Semarang'], 
            ['province_id' => 11, 'name' => 'Sragen'], 
            ['province_id' => 11, 'name' => 'Sukoharjo'], 
            ['province_id' => 11, 'name' => 'Surakarta'], 
            ['province_id' => 11, 'name' => 'Tegal'], 
            ['province_id' => 11, 'name' => 'Temanggung'], 
            ['province_id' => 11, 'name' => 'Wonogiri'], 
            ['province_id' => 11, 'name' => 'Wonosobo'],
            ['province_id' => 12, 'name' => 'Bangkalan'],
            ['province_id' => 12, 'name' => 'Banyuwangi'],
            ['province_id' => 12, 'name' => 'Batu'],
            ['province_id' => 12, 'name' => 'Blitar'],
            ['province_id' => 12, 'name' => 'Bojonegoro'],
            ['province_id' => 12, 'name' => 'Bondowoso'],
            ['province_id' => 12, 'name' => 'Gresik'],
            ['province_id' => 12, 'name' => 'Jember'],
            ['province_id' => 12, 'name' => 'Jombang'],
            ['province_id' => 12, 'name' => 'Kediri'],
            ['province_id' => 12, 'name' => 'Lamongan'],
            ['province_id' => 12, 'name' => 'Lumajang'],
            ['province_id' => 12, 'name' => 'Madiun'],
            ['province_id' => 12, 'name' => 'Magetan'],
            ['province_id' => 12, 'name' => 'Malang'],
            ['province_id' => 12, 'name' => 'Mojokerto'],
            ['province_id' => 12, 'name' => 'Nganjuk'],
            ['province_id' => 12, 'name' => 'Ngawi'],
            ['province_id' => 12, 'name' => 'Pacitan'],
            ['province_id' => 12, 'name' => 'Pamekasan'],
            ['province_id' => 12, 'name' => 'Pasuruan'],
            ['province_id' => 12, 'name' => 'Ponorogo'],
            ['province_id' => 12, 'name' => 'Probolinggo'],
            ['province_id' => 12, 'name' => 'Sampang'],
            ['province_id' => 12, 'name' => 'Sidoarjo'],
            ['province_id' => 12, 'name' => 'Situbondo'],
            ['province_id' => 12, 'name' => 'Sumenep'],
            ['province_id' => 12, 'name' => 'Surabaya'],
            ['province_id' => 12, 'name' => 'Trenggalek'],
            ['province_id' => 12, 'name' => 'Tuban'],
            ['province_id' => 12, 'name' => 'Tulungagung'],
            ['province_id' => 13, 'name' => 'Bengkayang'], 
            ['province_id' => 13, 'name' => 'Kapuas Hulu'], 
            ['province_id' => 13, 'name' => 'Kayong Utara'], 
            ['province_id' => 13, 'name' => 'Ketapang'], 
            ['province_id' => 13, 'name' => 'Kubu Raya'], 
            ['province_id' => 13, 'name' => 'Landak'], 
            ['province_id' => 13, 'name' => 'Melawi'], 
            ['province_id' => 13, 'name' => 'Pontianak'], 
            ['province_id' => 13, 'name' => 'Sambas'], 
            ['province_id' => 13, 'name' => 'Sanggau'], 
            ['province_id' => 13, 'name' => 'Sekadau'], 
            ['province_id' => 13, 'name' => 'Singkawang'], 
            ['province_id' => 13, 'name' => 'Sintang'],
            ['province_id' => 14, 'name' => 'Balangan'], 
            ['province_id' => 14, 'name' => 'Banjar'], 
            ['province_id' => 14, 'name' => 'Banjarbaru'], 
            ['province_id' => 14, 'name' => 'Banjarmasin'], 
            ['province_id' => 14, 'name' => 'Barito Kuala'], 
            ['province_id' => 14, 'name' => 'Hulu Sungai Selatan'], 
            ['province_id' => 14, 'name' => 'Hulu Sungai Tengah'], 
            ['province_id' => 14, 'name' => 'Hulu Sungai Utara'], 
            ['province_id' => 14, 'name' => 'Kotabaru'], 
            ['province_id' => 14, 'name' => 'Tabalong'], 
            ['province_id' => 14, 'name' => 'Tanah Bumbu'], 
            ['province_id' => 14, 'name' => 'Tanah Laut'], 
            ['province_id' => 14, 'name' => 'Tapin'],
            ['province_id' => 15, 'name' => 'Barito Selatan'],
            ['province_id' => 15, 'name' => 'Barito Timur'],
            ['province_id' => 15, 'name' => 'Barito Utara'],
            ['province_id' => 15, 'name' => 'Gunung Mas'],
            ['province_id' => 15, 'name' => 'Kapuas'],
            ['province_id' => 15, 'name' => 'Katingan'],
            ['province_id' => 15, 'name' => 'Kotawaringin Barat'],
            ['province_id' => 15, 'name' => 'Kotawaringin Timur'],
            ['province_id' => 15, 'name' => 'Lamandau'],
            ['province_id' => 15, 'name' => 'Murung Raya'],
            ['province_id' => 15, 'name' => 'Palangka Raya'],
            ['province_id' => 15, 'name' => 'Pulang Pisau'],
            ['province_id' => 15, 'name' => 'Seruyan'],
            ['province_id' => 15, 'name' => 'Sukamara'],
            ['province_id' => 16, 'name' => 'Balikpapan'], 
            ['province_id' => 16, 'name' => 'Berau'], 
            ['province_id' => 16, 'name' => 'Bontang'], 
            ['province_id' => 16, 'name' => 'Bulongan'], 
            ['province_id' => 16, 'name' => 'Kutai Barat'], 
            ['province_id' => 16, 'name' => 'Kutai Kartanegara'], 
            ['province_id' => 16, 'name' => 'Kutai Timur'], 
            ['province_id' => 16, 'name' => 'Malinau'], 
            ['province_id' => 16, 'name' => 'Nunukan'], 
            ['province_id' => 16, 'name' => 'Pasir'], 
            ['province_id' => 16, 'name' => 'Penajam Paser Utara'], 
            ['province_id' => 16, 'name' => 'Samarinda'], 
            ['province_id' => 16, 'name' => 'Tana Tidung'], 
            ['province_id' => 16, 'name' => 'Tarakan'],
            ['province_id' => 17, 'name' => 'Bulungan'], 
            ['province_id' => 17, 'name' => 'Kota Tarakan'], 
            ['province_id' => 17, 'name' => 'Malinau'], 
            ['province_id' => 17, 'name' => 'Nunukan'], 
            ['province_id' => 17, 'name' => 'Tana Tidung'], 
            ['province_id' => 18, 'name' => 'Batam'],
            ['province_id' => 18, 'name' => 'Bintan'],
            ['province_id' => 18, 'name' => 'Karimun'],
            ['province_id' => 18, 'name' => 'Kepulauan Anambas'],
            ['province_id' => 18, 'name' => 'Lingga'],
            ['province_id' => 18, 'name' => 'Natuna'],
            ['province_id' => 18, 'name' => 'Tanjungpinang'],
            ['province_id' => 19, 'name' => 'Bandar Lambung'], 
            ['province_id' => 19, 'name' => 'Lampung Barat'], 
            ['province_id' => 19, 'name' => 'Lampung Selatan'], 
            ['province_id' => 19, 'name' => 'Lampung Tengah'], 
            ['province_id' => 19, 'name' => 'Lampung Timur'], 
            ['province_id' => 19, 'name' => 'Lampung Utara'], 
            ['province_id' => 19, 'name' => 'Mesuji'], 
            ['province_id' => 19, 'name' => 'Metro'], 
            ['province_id' => 19, 'name' => 'Pesawaran'], 
            ['province_id' => 19, 'name' => 'Pringsewu'], 
            ['province_id' => 19, 'name' => 'Tanggamus'], 
            ['province_id' => 19, 'name' => 'Tulang Bawang'], 
            ['province_id' => 19, 'name' => 'Tulang Bawang Barat'], 
            ['province_id' => 19, 'name' => 'Way Kanan'], 
            ['province_id' => 20, 'name' => 'Halmahera Barat'], 
            ['province_id' => 20, 'name' => 'Halmahera Selatan'], 
            ['province_id' => 20, 'name' => 'Halmahera Tengah'], 
            ['province_id' => 20, 'name' => 'Halmahera Timur'],
            ['province_id' => 20, 'name' => 'Halmahera Utara'],
            ['province_id' => 20, 'name' => 'Kepulauan Sula'], 
            ['province_id' => 20, 'name' => 'Pulau Morotai'],
            ['province_id' => 20, 'name' => 'Ternate'], 
            ['province_id' => 20, 'name' => 'Tidore Kepulauan'], 
            ['province_id' => 21, 'name' => 'Ambon'],
            ['province_id' => 21, 'name' => 'Buru'],
            ['province_id' => 21, 'name' => 'Buru Selatan'], 
            ['province_id' => 21, 'name' => 'Halmahera Barat'], 
            ['province_id' => 21, 'name' => 'Halmahera Selatan'], 
            ['province_id' => 21, 'name' => 'Halmahera Tengah'], 
            ['province_id' => 21, 'name' => 'Halmahera Timur'],
            ['province_id' => 21, 'name' => 'Halmahera Utara'],
            ['province_id' => 21, 'name' => 'Kepulauan Aru'],
            ['province_id' => 21, 'name' => 'Kepulauan Sula'],
            ['province_id' => 21, 'name' => 'Maluku Barat Daya'],
            ['province_id' => 21, 'name' => 'Maluku Tengah'],
            ['province_id' => 21, 'name' => 'Maluku Tenggara'],
            ['province_id' => 21, 'name' => 'Maluku Tenggara Barat'],
            ['province_id' => 21, 'name' => 'Pulau Morotai'],
            ['province_id' => 21, 'name' => 'Seram Bagian Barat'],
            ['province_id' => 21, 'name' => 'Seram Bagian Timur'],
            ['province_id' => 21, 'name' => 'Ternate'],
            ['province_id' => 21, 'name' => 'Tidore Kepulauan'],
            ['province_id' => 21, 'name' => 'Tual'],
            ['province_id' => 22, 'name' => 'Bima'], 
            ['province_id' => 22, 'name' => 'Dompu'], 
            ['province_id' => 22, 'name' => 'Lombok Barat'], 
            ['province_id' => 22, 'name' => 'Lombok Tengah'], 
            ['province_id' => 22, 'name' => 'Lombok Timur'], 
            ['province_id' => 22, 'name' => 'Lombok Utara'], 
            ['province_id' => 22, 'name' => 'Mataram'], 
            ['province_id' => 22, 'name' => 'Sumbawa'], 
            ['province_id' => 22, 'name' => 'Sumbawa Barat'],
            ['province_id' => 23, 'name' => 'Alor'], 
            ['province_id' => 23, 'name' => 'Belu'], 
            ['province_id' => 23, 'name' => 'Ende'], 
            ['province_id' => 23, 'name' => 'Flores Timur'], 
            ['province_id' => 23, 'name' => 'Kupang'], 
            ['province_id' => 23, 'name' => 'Lembata'], 
            ['province_id' => 23, 'name' => 'Manggarai'], 
            ['province_id' => 23, 'name' => 'Manggarai Barat'], 
            ['province_id' => 23, 'name' => 'Manggarai Timur'], 
            ['province_id' => 23, 'name' => 'Nagekeo'], 
            ['province_id' => 23, 'name' => 'Ngada'], 
            ['province_id' => 23, 'name' => 'Rote Ndao'], 
            ['province_id' => 23, 'name' => 'Sabu Raijua'], 
            ['province_id' => 23, 'name' => 'Sikka'], 
            ['province_id' => 23, 'name' => 'Sumba Barat'], 
            ['province_id' => 23, 'name' => 'Sumba Barat Daya'], 
            ['province_id' => 23, 'name' => 'Sumba Tengah'], 
            ['province_id' => 23, 'name' => 'Sumba Timur'], 
            ['province_id' => 23, 'name' => 'Timor Tengah Selatan'], 
            ['province_id' => 23, 'name' => 'Timor Tengah Utara'],
            ['province_id' => 24, 'name' => 'Asmat'], 
            ['province_id' => 24, 'name' => 'Biak Numfor'], 
            ['province_id' => 24, 'name' => 'Bintuni'], 
            ['province_id' => 24, 'name' => 'Boven Digoel'], 
            ['province_id' => 24, 'name' => 'Deiyai'], 
            ['province_id' => 24, 'name' => 'Dogiyai'], 
            ['province_id' => 24, 'name' => 'Fak Fak'], 
            ['province_id' => 24, 'name' => 'Fakfak'], 
            ['province_id' => 24, 'name' => 'Intan Jaya'], 
            ['province_id' => 24, 'name' => 'Jayapura'], 
            ['province_id' => 24, 'name' => 'Jayawijaya'], 
            ['province_id' => 24, 'name' => 'Kaimana'], 
            ['province_id' => 24, 'name' => 'Keerom'], 
            ['province_id' => 24, 'name' => 'Lanny Jaya'], 
            ['province_id' => 24, 'name' => 'Mamberamo Raya'], 
            ['province_id' => 24, 'name' => 'Mamberamo Tengah'], 
            ['province_id' => 24, 'name' => 'Manokwari'], 
            ['province_id' => 24, 'name' => 'Mappi'], 
            ['province_id' => 24, 'name' => 'Maybrat'], 
            ['province_id' => 24, 'name' => 'Merauke'], 
            ['province_id' => 24, 'name' => 'Mimika'], 
            ['province_id' => 24, 'name' => 'Nabire'], 
            ['province_id' => 24, 'name' => 'Nduga'], 
            ['province_id' => 24, 'name' => 'Paniai'], 
            ['province_id' => 24, 'name' => 'Pegunungan Bintang'], 
            ['province_id' => 24, 'name' => 'Puncak'], 
            ['province_id' => 24, 'name' => 'Puncak Jaya'], 
            ['province_id' => 24, 'name' => 'Raja Ampat'], 
            ['province_id' => 24, 'name' => 'Sarmi'], 
            ['province_id' => 24, 'name' => 'Sorong'], 
            ['province_id' => 24, 'name' => 'Sorong Selatan'], 
            ['province_id' => 24, 'name' => 'Supiori'], 
            ['province_id' => 24, 'name' => 'Tambrauw'], 
            ['province_id' => 24, 'name' => 'Teluk Bintuni'], 
            ['province_id' => 24, 'name' => 'Teluk Wondama'], 
            ['province_id' => 24, 'name' => 'Tolikara'], 
            ['province_id' => 24, 'name' => 'Waropen'], 
            ['province_id' => 24, 'name' => 'Yahukimo'], 
            ['province_id' => 24, 'name' => 'Yalimo'], 
            ['province_id' => 24, 'name' => 'Yapen Waropen'], 
            ['province_id' => 25, 'name' => 'Bengkalis'], 
            ['province_id' => 25, 'name' => 'Dumai'], 
            ['province_id' => 25, 'name' => 'Indragiri Hilir'], 
            ['province_id' => 25, 'name' => 'Indragiri Hulu'], 
            ['province_id' => 25, 'name' => 'Kampar'], 
            ['province_id' => 25, 'name' => 'Kepulauan Meranti'], 
            ['province_id' => 25, 'name' => 'Kuantan Singingi'], 
            ['province_id' => 25, 'name' => 'Pekan Baru'], 
            ['province_id' => 25, 'name' => 'Pelalawan'], 
            ['province_id' => 25, 'name' => 'Rokan Hilir'], 
            ['province_id' => 25, 'name' => 'Rokan Hulu'], 
            ['province_id' => 25, 'name' => 'Siak'],
            ['province_id' => 26, 'name' => 'Bantaeng'],
            ['province_id' => 26, 'name' => 'Barru'],
            ['province_id' => 26, 'name' => 'Bone'],
            ['province_id' => 26, 'name' => 'Bulukumba'],
            ['province_id' => 26, 'name' => 'Enrekang'],
            ['province_id' => 26, 'name' => 'Gowa'],
            ['province_id' => 26, 'name' => 'Jeneponto'],
            ['province_id' => 26, 'name' => 'Luwu'],
            ['province_id' => 26, 'name' => 'Luwu Timur'],
            ['province_id' => 26, 'name' => 'Luwu Utara'],
            ['province_id' => 26, 'name' => 'Majene'],
            ['province_id' => 26, 'name' => 'Makassar'],
            ['province_id' => 26, 'name' => 'Mamasa'],
            ['province_id' => 26, 'name' => 'Mamuju'],
            ['province_id' => 26, 'name' => 'Mamuju Utara'],
            ['province_id' => 26, 'name' => 'Maros'],
            ['province_id' => 26, 'name' => 'Palopo'],
            ['province_id' => 26, 'name' => 'Pangkajene Kepulauan'],
            ['province_id' => 26, 'name' => 'Pare-pare'],
            ['province_id' => 26, 'name' => 'Pinrang'],
            ['province_id' => 26, 'name' => 'Polewali Mandar'],
            ['province_id' => 26, 'name' => 'Selayar'],
            ['province_id' => 26, 'name' => 'Sidenreng Rappang'],
            ['province_id' => 26, 'name' => 'Sinjai'],
            ['province_id' => 26, 'name' => 'Soppeng'],
            ['province_id' => 26, 'name' => 'Takalar'],
            ['province_id' => 26, 'name' => 'Tana Toraja'],
            ['province_id' => 26, 'name' => 'Toraja Utara'],
            ['province_id' => 26, 'name' => 'Wajo'],
            ['province_id' => 27, 'name' => 'Banggai'], 
            ['province_id' => 27, 'name' => 'Banggai Kepulauan'], 
            ['province_id' => 27, 'name' => 'Buol'], 
            ['province_id' => 27, 'name' => 'Donggala'], 
            ['province_id' => 27, 'name' => 'Morowali'], 
            ['province_id' => 27, 'name' => 'Palu'], 
            ['province_id' => 27, 'name' => 'Parigi Moutong'], 
            ['province_id' => 27, 'name' => 'Poso'], 
            ['province_id' => 27, 'name' => 'Sigi'], 
            ['province_id' => 27, 'name' => 'Tojo Una-una'], 
            ['province_id' => 27, 'name' => 'Toli-toli'], 
            ['province_id' => 28, 'name' => 'Bau Bau'],
            ['province_id' => 28, 'name' => 'Bombana'],
            ['province_id' => 28, 'name' => 'Buton'],
            ['province_id' => 28, 'name' => 'Buton Utara'],
            ['province_id' => 28, 'name' => 'Kendari'],
            ['province_id' => 28, 'name' => 'Kolaka'],
            ['province_id' => 28, 'name' => 'Kolaka Utara'],
            ['province_id' => 28, 'name' => 'Konawe'],
            ['province_id' => 28, 'name' => 'Konawe Selatan'],
            ['province_id' => 28, 'name' => 'Konawe Utara'],
            ['province_id' => 28, 'name' => 'Muna'],
            ['province_id' => 28, 'name' => 'Wakatobi'],
            ['province_id' => 29, 'name' => 'Bitung'],
            ['province_id' => 29, 'name' => 'Bolaang Mongondow'],
            ['province_id' => 29, 'name' => 'Bolaang Mongondow Selatan'],
            ['province_id' => 29, 'name' => 'Bolaang Mongondow Timur'],
            ['province_id' => 29, 'name' => 'Bolaang Mongondow Utara'],
            ['province_id' => 29, 'name' => 'Kepualuan Talaud'],
            ['province_id' => 29, 'name' => 'Kepualuan Sangihe'],
            ['province_id' => 29, 'name' => 'Kotamobagu'],
            ['province_id' => 29, 'name' => 'Manado'],
            ['province_id' => 29, 'name' => 'Minahasa'],
            ['province_id' => 29, 'name' => 'Minahasa Selatan'],
            ['province_id' => 29, 'name' => 'Minahasa Tenggara'],
            ['province_id' => 29, 'name' => 'Minahasa Utara'],
            ['province_id' => 29, 'name' => 'Siau Tagulandang Biaro'],
            ['province_id' => 29, 'name' => 'Tomohon'],
            ['province_id' => 30, 'name' => 'Agam'], 
            ['province_id' => 30, 'name' => 'Bukittinggi'], 
            ['province_id' => 30, 'name' => 'Dharmasraya'], 
            ['province_id' => 30, 'name' => 'Kepulauan Mentawai'], 
            ['province_id' => 30, 'name' => 'Lima Puluh Koto'], 
            ['province_id' => 30, 'name' => 'Padang'], 
            ['province_id' => 30, 'name' => 'Padang Panjang'], 
            ['province_id' => 30, 'name' => 'Pariaman'], 
            ['province_id' => 30, 'name' => 'Pasaman'], 
            ['province_id' => 30, 'name' => 'Pasaman Barat'], 
            ['province_id' => 30, 'name' => 'Payakumbuh'], 
            ['province_id' => 30, 'name' => 'Pesisir Selatan'], 
            ['province_id' => 30, 'name' => 'Sawah Lunto'], 
            ['province_id' => 30, 'name' => 'Sijunjung'], 
            ['province_id' => 30, 'name' => 'Solok'], 
            ['province_id' => 30, 'name' => 'Solok Selatan'], 
            ['province_id' => 30, 'name' => 'Tanah Datar'],
            ['province_id' => 31, 'name' => 'Banyu Asin'], 
            ['province_id' => 31, 'name' => 'Empat Lawang'], 
            ['province_id' => 31, 'name' => 'Lahat'], 
            ['province_id' => 31, 'name' => 'Lubuk Lingga'], 
            ['province_id' => 31, 'name' => 'Muara Enim'], 
            ['province_id' => 31, 'name' => 'Musi Banyu Asin'], 
            ['province_id' => 31, 'name' => 'Musi Rawas'], 
            ['province_id' => 31, 'name' => 'Ogan Ilir'], 
            ['province_id' => 31, 'name' => 'Oki'], 
            ['province_id' => 31, 'name' => 'Oku'], 
            ['province_id' => 31, 'name' => 'Oku Selatan'], 
            ['province_id' => 31, 'name' => 'Oku Timur'], 
            ['province_id' => 31, 'name' => 'Pagar Alam'], 
            ['province_id' => 31, 'name' => 'Palembang'], 
            ['province_id' => 31, 'name' => 'Prabumulih'], 
            ['province_id' => 32, 'name' => 'Asahan'],
            ['province_id' => 32, 'name' => 'Batu Bara'],
            ['province_id' => 32, 'name' => 'Binjai'],
            ['province_id' => 32, 'name' => 'Dairi'],
            ['province_id' => 32, 'name' => 'Deli Serdang'],
            ['province_id' => 32, 'name' => 'Gunung Sitoli'],
            ['province_id' => 32, 'name' => 'Humbang Hasundutan'],
            ['province_id' => 32, 'name' => 'Karo'],
            ['province_id' => 32, 'name' => 'Labuhan Batu'],
            ['province_id' => 32, 'name' => 'Labuhan Batu Selatan'],
            ['province_id' => 32, 'name' => 'Labuhan Batu Utara'],
            ['province_id' => 32, 'name' => 'Langkat'],
            ['province_id' => 32, 'name' => 'Mandailing Natal'],
            ['province_id' => 32, 'name' => 'Medan'],
            ['province_id' => 32, 'name' => 'Nias'],
            ['province_id' => 32, 'name' => 'Nias Barat'],
            ['province_id' => 32, 'name' => 'Nias Selatan'],
            ['province_id' => 32, 'name' => 'Nias Utara'],
            ['province_id' => 32, 'name' => 'Padang Lawas'],
            ['province_id' => 32, 'name' => 'Padang Lawas Utara'],
            ['province_id' => 32, 'name' => 'Padang Sidempuan'],
            ['province_id' => 32, 'name' => 'Pematang Siantar'],
            ['province_id' => 32, 'name' => 'Samosir'],
            ['province_id' => 32, 'name' => 'Serdang Bedagai'],
            ['province_id' => 32, 'name' => 'Sibolga'],
            ['province_id' => 32, 'name' => 'Simalungun'],
            ['province_id' => 32, 'name' => 'Tanjung Balai'],
            ['province_id' => 32, 'name' => 'Tapanuli Selatan'],
            ['province_id' => 32, 'name' => 'Tapanuli Tengah'],
            ['province_id' => 32, 'name' => 'Tapanuli Utara'],
            ['province_id' => 32, 'name' => 'Tebing Tinggi'],
            ['province_id' => 32, 'name' => 'Toba Samosir'],
            ['province_id' => 33, 'name' => 'Majene'], 
            ['province_id' => 33, 'name' => 'Mamasa'], 
            ['province_id' => 33, 'name' => 'Mamuju'], 
            ['province_id' => 33, 'name' => 'Mamuju Utara'], 
            ['province_id' => 33, 'name' => 'Polewali Mandar'],
            ['province_id' => 34, 'name' => 'Bintuni'], 
            ['province_id' => 34, 'name' => 'Fak Fak'], 
            ['province_id' => 34, 'name' => 'Kaimana'], 
            ['province_id' => 34, 'name' => 'Manokwari'], 
            ['province_id' => 34, 'name' => 'Maybrat'], 
            ['province_id' => 34, 'name' => 'Raja Ampat'], 
            ['province_id' => 34, 'name' => 'Sorong'], 
            ['province_id' => 34, 'name' => 'Sorong Selatan'], 
            ['province_id' => 34, 'name' => 'Tambrauw'], 
            ['province_id' => 34, 'name' => 'Teluk Wondama'],
            ['province_id' => 6, 'name' => 'Bantul'],
            ['province_id' => 9, 'name' => 'Sarolangun'],
            ['province_id' => 9, 'name' => 'Sungai Penuh'],
            ['province_id' => 32, 'name' => 'Papak Bharat'],

        ];

        foreach($cities as $city) {
            City::create($city);
        }
    }
}
